FILENAME_KEYS = "paste_keys"
FILENAME_USERS = "paste_users"
FILENAME_PASTES_WITH_TITLE = "pastes"
FILENAME_KEYWORDS = "keywords"
FILENAME_IMP_PASTES = "Important_pastes"
DIR_PATH = "./"
FILENAME_EXT = ".txt"